Docker:
  - 'Dockerfile'

Kubernetes:
  - 'k8s/**'
  - 'templates_yamls/**'
  - 'eks-config/**'

Gradle:
  - 'gradle/**'
  - 'gradlew'
  - 'gradlew.bat'
  - 'settings.gradle'
  - 'gradle.properties'

Documentation:
  - '**/*.md'

Github-files:
  - '.github/**'
