Docker:
  - 'Dockerfile'

Kubernetes:
  - 'k8/**'
  - 'templates_yamls/**'
  - 'eks-config/**'
  - 'template_yaml/**'
  - 'scripts/**'
  - 'Dockerfile'

Data:
  - 'data/**'

Gradle:
  - 'gradle/**'
  - 'gradlew'
  - 'gradlew.bat'
  - 'settings.gradle'
  - 'gradle.properties'
  - 'build.gradle'

Documentation:
  - '**/*.md'

Github-files:
  - '.github/**'

Java:
  - '**/*.java'
