apiVersion: v1
kind: Service
metadata:
  name: ppdt-level-site-16-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    pod: ppdt-level-site-16-deploy
  type: NodePort
