apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppdt-server-deploy
  labels:
    app: ppdt-server-deploy
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ppdt-server-deploy
  template:
    metadata:
      labels:
        pod: ppdt-server-deploy
    spec:
      containers:
        - name: ppdt-server-deploy
          image: andrewquijano92/ppdt
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: TREE_ROLE
              value: "SERVER"

            - name: PRECISION
              value: "2"

            - name: PORT_NUM
              value: "9000"

            - name: LEVEL_SITE_DOMAINS
              value: "ppdt-level-site-01-service,ppdt-level-site-02-service,ppdt-level-site-03-service,ppdt-level-site-04-service,ppdt-level-site-05-service,ppdt-level-site-06-service,ppdt-level-site-07-service,ppdt-level-site-08-service,ppdt-level-site-09-service,ppdt-level-site-10-service"

            - name: CLIENT
              value: "ppdt-client-service"

            - name: GRADLE_USER_HOME
              value: "gradle_user_home"

            - name: KEYSTORE
              value: "keystore"

            - name: ALIAS
              value: "appsec"

            - name: CERTIFICATE
              value: "ppdt-certificate"
              
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ppdt-secrets
                  key: keystore-pass
