# https://eksctl.io/usage/schema/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ppdt
  region: us-east-2
  version: "1.27"
managedNodeGroups:
- name: primary
  instanceType: t2.small
  minSize: 3
  maxSize: 15
  spot: true