# https://eksctl.io/usage/schema/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ppdt
  region: us-east-2
  version: "1.27"
managedNodeGroups:
- name: primary
  instanceType: m5.large
  desiredCapacity: 12
  minSize: 12
  maxSize: 15
  spot: true