# https://eksctl.io/usage/schema/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ppdt
  region: us-east-2
  version: "1.27"

# Managed Node Groups show up on AWS console
# Label is necessary so I can target where the pods go with kubectl apply
# For best performance, I am isolating each level-site pod to its own node.
managedNodeGroups:
# Currently I have 10 level-sites
- name: level-sites
  instanceType: t2.large
  labels: { role: level-site }
  minSize: 12
  maxSize: 15
  desiredCapacity: 12
