apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: upper-tree
  region: us-east-2
  version: "1.29"

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

managedNodeGroups:
  - name: upper-nodes
    instanceType: t2.medium
    minSize: 5
    maxSize: 7
    desiredCapacity: 5