name: Build Gradle project

on:
  workflow_dispatch:
  pull_request:

# Automatically cancel any previous workflow on a new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      ALIAS: appsec
      KEYSTORE: keystore
      PASSWORD: ${{ secrets.PASSWORD }}
      CERTIFICATE: ppdt-certificate

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Install Graphviz to visualize trees
      run: sudo apt-get install -y graphviz

    - name: Setup Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'gradle'

    - name: Run Gradle Testing and Create Coverage Report
      run: ./gradlew test jacocoTestReport -PcreateReports

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
