name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      ALIAS: andrew
      KEYSTORE: andrew_keystore
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get install -y graphviz

    - name: Setup Gradle
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'gradle'

    - name: Create keystore for local use
      run: sh create_keystore.sh

    - name: Run Gradle Testing
      run: sh gradlew build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}