name: Build Gradle project

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-gradle-project:
    if: github.event.pull_request.merged == false && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      ALIAS: appsec
      KEYSTORE: keystore
      PASSWORD: ${{ secrets.PASSWORD }}
      CERTIFICATE: ppdt-certificate

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Install Graphviz to visualize trees
      run: sudo apt-get install -y graphviz

    - name: Setup Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'gradle'

    - name: Run Gradle Testing
      run: sh gradlew build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
