apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppdt-client-deploy
  labels:
    app: ppdt-client-deploy
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ppdt-client-deploy
  template:
    metadata:
      labels:
        pod: ppdt-client-deploy
    spec:
      containers:
        - name: ppdt-client-deploy
          image: andrewquijano92/ppdt
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: CLIENT_HOSTNAME
              value: "ppdt-client-service"

            - name: TREE_ROLE
              value: "CLIENT"

            - name: PRECISION
              value: "2"

            - name: PORT_NUM
              value: "9000"

            - name: PPDT_KEY_SIZE
              value: "2048"

            - name: SERVER
              value: "ppdt-server-service"

            - name: GRADLE_USER_HOME
              value: "gradle_user_home"

            - name: KEYSTORE
              value: "keystore"

            - name: ALIAS
              value: "appsec"

            - name: CERTIFICATE
              value: "ppdt-certificate"

            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ppdt-secrets
                  key: keystore-pass
